### ISSUE TITLE
Some more dependencies

### ISSUE THREAD

**Issue by etairaz** [mangate/SelfGPT#5]
I took the time to run this on a fresh docker container, and was missing a few dependencies after running pip install, like yaml and plotly and others.

Here is my pip freeze output in case you are interested:
aiohttp==3.8.3
aiosignal==1.3.1
async-timeout==4.0.2
attrs==22.2.0
certifi==2022.12.7
charset-normalizer==2.1.1
click==8.1.3
contourpy==1.0.7
cycler==0.11.0
Flask==2.2.2
fonttools==4.38.0
frozenlist==1.3.3
idna==3.4
itsdangerous==2.1.2
Jinja2==3.1.2
joblib==1.2.0
kiwisolver==1.4.4
MarkupSafe==2.1.2
matplotlib==3.6.3
multidict==6.0.4
numpy==1.24.1
openai==0.26.4
packaging==23.0
pandas==1.5.3
Pillow==9.4.0
plotly==5.13.0
PyJWT==2.6.0
pyparsing==3.0.9
python-dateutil==2.8.2
pytz==2022.7.1
PyYAML==6.0
requests==2.28.2
scikit-learn==1.2.1
scipy==1.10.0
six==1.16.0
tenacity==8.1.0
threadpoolctl==3.1.0
tqdm==4.64.1
twilio==7.16.2
urllib3==1.26.14
Werkzeug==2.2.2
yarl==1.8.2

**Comment by paviad** [comment]
Do I need to edit my `requirements.txt` and add all the above?

**Comment by mangate** [comment]
The important things are already added to the requirements.txt file
