### ISSUE TITLE
guide how to deploy

### ISSUE THREAD

**Issue by chiptus** [mangate/SelfGPT#6]
I see in the readme it's suggested to run locally with ngrok. it would be nice if we provide a way to deploy it to the cloud

**Comment by paviad** [comment]
I've prepared a PR that is ready to be deployed to Azure. I have deployed my own bot to Azure and it now has 100% uptime (with some caveats). I am waiting for the current PR #15 to be approved before submitting mine to avoid too many conflicts as it is based on that one.

**Comment by paviad** [comment]
In the mean time, I invite you to look at my fork at https://github.com/paviad/SelfGPT

**Comment by mangate** [comment]
This is amazing, I was looking fo it. Will merge PR15 and than we can merge yours. One question, why does the script has to run on my local machine before I deploy it on Azure?

**Comment by mangate** [comment]
PR15 is now merged

**Comment by paviad** [comment]
Because it extracts configuration from the local user directory

**Comment by paviad** [comment]
PR #17 submitted

**Comment by paviad** [comment]
Can this be closed?

**Comment by mangate** [comment]
Yes. Great work!!
